### PR TITLE
fix default venue for agenda

### PR DESCRIPTION
**Pull request by datachomp**
This will move the default agenda from  TNHH to  TBD.

cc @ryoe @carmalou

### CODE REVIEW

**Comment by carmalou** [comment]
ummm, where are the venue ids so I can review?

**Comment by ryoe** [comment]
@datachomp o_O What's happening here?

**Comment by datachomp** [comment]
@carmalou 
```
 select * from venues where id = 0;
┌────┬───────┬───────────────────────┬────────────────────────────┬────────────────────────────┐
│ id │ venue │       map_link        │         created_at         │         updated_at         │
├────┼───────┼───────────────────────┼────────────────────────────┼────────────────────────────┤
│  0 │ TBD   │ http://nerdbeers.com/ │ 2016-07-21 22:07:15.572933 │ 2016-07-21 22:07:15.572933 │
└────┴───────┴───────────────────────┴────────────────────────────┴────────────────────────────┘
(1 row)

Time: 194.241 ms
```

**Comment by ryoe** [comment]
@carmalou: http://nerdbeers.com/api/venues

**Comment by carmalou** [comment]
👍 lgtm

**Comment by ryoe** [comment]
Do eeet! 👍

**Comment by datachomp** [comment]
taking this straight to prod - day of event.  YODO!!!

**Comment by ryoe** [comment]
HA! merged just before I +1!

**Comment by ryoe** [comment]
YODO? You only die once?

**Comment by datachomp** [comment]
Opps. I meant Yoda

**Pull request merged**
